### ISSUE TITLE
Build config to create NON minified versions

### ISSUE THREAD

**Issue by alejandroscotti** [mambojs/mambo-ui#34]
In the Build configurations for **ALL repos** create a set of **js/css** files that are NOT minified, this way we can analyze the output file. When the output is minified and uglified it's impossible to inspect it and read it. Also, as a user of the ecosystem, I may want to work with the NOT minified version so I can read it and then during my web app build process I can do my own minify along with all my other production files.

**Comment by javierbasualdo** [comment]
https://github.com/mambojs/mambo-ui/pull/39
